### ISSUE TITLE
How to debug a data matrix ErrorCorrection error?

### ISSUE THREAD

**Issue by jonasthewolf** [jannschu/datamatrix-rs#1]
I have found a data matrix and trying to decode it.
I tried using datamatrix-rs wit the following code:

    fn main() {
        let input_str = std::fs::read_to_string("datamatrix.txt").unwrap();
        let pixels = input_str.chars().filter_map(|b| match b {
            '1' => Some(true),
            '0' => Some(false),
            _ => None,
        }).collect::<Vec<_>>();
        let width = 48;
        let data = datamatrix::DataMatrix::decode(&pixels, width);
        println!("{:?}", data.unwrap());
    }`

Here is the contents of datamatrix.txt

    101010101010101010101010101010101010101010101010
    100101001000001001010001101000010101010010111101
    110010100001000111101110111111011100101000001100
    110001110000001011000011100110101100011100010001
    101011100011100001000110110100011010111000011000
    100010001001011011001101101100010000100010000101
    100011000101100010011010111001110000110001101000
    110000001001100001110111100110111100000010000001
    100101000111001011100000100010100101010001011110
    111000111111000001001011110011010110001111110101
    110001100110001000001100100111011100011001100010
    100011010001101100100001111010100000110100100111
    111010110010111000011100101100111110101100011000
    110010001001011010011101101101010100100010100001
    111101100110000101101110101000000111011001100000
    111111111111111111111111111111111111111111111111

Is there any way to debug the data matrix to tell where the input data is wrong?
Thanks.

**Comment by jannschu** [comment]
Hi,

sorry for this super late answer. Seems I did not see the notification, will check later.

This is your code visualized:

<img width="309" alt="datamatrix" src="https://user-images.githubusercontent.com/17914/166420060-39a5ce30-5485-4fb5-96d0-ce5a0bf98261.png">

I tried different scanners and they also fail, but you might already know that.

An `ErrorCorrection` error signals that the error correction was either not done correctly when the datamatrix was encoded or there were too many errors, ie. 0 and 1 that are falsely detected. This is the best we can do I think since we do not know which 0 and 1 are wrong, only that there are too many (most likely).

**Comment by jannschu** [comment]
Did take a closer look, might be helpful to you or not: The reason why error correction fails in this case is that the error locator polynomial has degree 14 but only two zeros (should be 14). The explanation stays the same, however.

By the way, skipping error correction one would get the string

```
3#4K2907468B    #HX03SX315#*K19LAK-KRO20.02.1800000028*=0784j\u{2}23/68\\
```

**Comment by jonasthewolf** [comment]
@jannschu Thanks for the answer. Is there an easy way to produce that visualisation. I would like to check if I correctly set up the 1s and 0s. 😉

**Comment by jannschu** [comment]
Yes, I used this code:

```rust
let (matrix_map, size) =
    datamatrix::placement::MatrixMap::try_from_bits(&pixels, width).unwrap();
println!("{}", matrix_map.bitmap().unicode());
println!("{:?}", size);
```

**Comment by jonasthewolf** [comment]
Can it be a problem that the data is actually inverted?
I at least get different errors when putting in the inverted:
ErrorCorrection(Malfunction) vs PixelConversion(Alignment).

**Comment by jannschu** [comment]
No. If you invert 0 and 1 the library will stop even earlier. In this case because the alignment pattern around is not correct (black "L" and the alternating lines).

For visualization you can either print dark on light or light on dark. But after detection this must be mapped correctly to `true` and `false`.

**Comment by jonasthewolf** [comment]
Great, thank you very much for support!
